Blog see more posts
Agaetis-IT/agaetis-web-front pull request #44
Opened 2021-04-08 12:44 UTC by CedricKlodzinski

Incremental loading with 'See more' button.
Search bar + categories handled.
Loading spinner in the 'See more' button when loading next posts

2021-04-09 08:45 UTC, bahumbert requested changes

2021-04-09 08:45 UTC, bahumbert commented on src/pages/blog.css
> +    animation-fill-mode: none !important;
Utiliser plutôt le spinner que l'on a déjà (séparer dans un nouveau composant si besoin) 👌

2021-04-09 08:45 UTC, bahumbert commented on src/pages/blog.tsx
> +                    setTimeout(() => {
Pas de logique comme ça en inline, rajoute une fonction 👍

2021-04-09 08:45 UTC, bahumbert commented on src/pages/blog.tsx
> +  const [ideas, setIdeas] = useState(ideasDescription.sort(compareIdeasByDate))
Normalement ce sort n'a plus lieu d'être non ?

2021-04-09 08:45 UTC, bahumbert commented on src/pages/blog.tsx
> +  function applyFilters(data: any[], changedCategory?: string, changedSearchFilter?: string) {
Pas de any 😋

2021-04-09 08:45 UTC, bahumbert commented on src/pages/blog.tsx
> +    setIdeas(ideas.concat(data).sort(compareIdeasByDate))
idem sort

2021-04-09 08:45 UTC, bahumbert commented on src/pages/blog.tsx
> +      if (newData.length < 7) continueFetch = false
Tout ça sera simplifié du coup avec la pagination à 9 partout n°2

2021-04-09 08:45 UTC, bahumbert commented on src/pages/blog.tsx
> +      const { [0]: newData } = await Promise.all([getIdeasByPage(i)])
Tout ça sera simplifié du coup avec la pagination à 9 partout !

2021-04-09 08:45 UTC, bahumbert commented on src/pages/blog.tsx
> +  }
Tu peux virer tout ça aussi 👌

2021-04-09 08:45 UTC, bahumbert commented on src/pages/blog.tsx
> +  }
Cette fonction est stateless : sort là du composant, je la mettrais d'ailleurs dans un fichier à part
Et tu peux refacto avec un switch ça sera plus lisible 👍

2021-04-09 08:45 UTC, bahumbert commented on src/pages/blog.tsx
> +  const [loadedPages, setLoadedPages] = useState(1)
`lastPage` ou `currentPage` serait plus exact non ?

2021-04-09 08:53 UTC, bahumbert requested changes

2021-04-09 08:53 UTC, bahumbert commented on src/pages/blog.tsx
> +  const [isLoadingMorePosts, setIsLoadingMorePosts] = useState(false)
Plutôt un seul state de loader pour faire au plus simple 👍

2021-04-09 08:53 UTC, bahumbert commented on src/pages/blog.tsx
> +    console.log(searchBarFilter)
console.log 😋

2021-04-09 08:53 UTC, bahumbert commented on src/pages/blog.tsx
> +        button.classList.add('invisible')
On invite de toucher au DOM comme ça dans une fonction, utilise plutôt le state pour changer les classes directement dans le JSX 👍

2021-04-12 15:38 UTC, CedricKlodzinski commented on src/pages/blog.css
> +    animation-fill-mode: none !important;
Voir la branche loading-spinner

2021-04-12 17:25 UTC, bahumbert commented on src/pages/blog.tsx
> +  }
Parfait ! 👌

2021-04-12 17:30 UTC, bahumbert commented on src/components/Ideas.tsx
> +            )}
C'est normal ça ? 😋

2021-04-12 17:31 UTC, bahumbert commented on src/pages/blog/[slug].tsx
> +  query: { slug: string }
Quelque chose comme `articleUrlId` ne serait pas plus explicite ?

2021-04-12 17:32 UTC, bahumbert commented on src/pages/blog/[slug].tsx
> +  if (query.slug) {
J'inverserai ce if pour que ça soit plus lisible 👍

2021-04-12 17:33 UTC, bahumbert approved these changes

2021-04-13 07:38 UTC, merged