Home page style
Agaetis-IT/agaetis-web-front pull request #67
Opened 2021-05-18 09:24 UTC by CedricKlodzinski

2021-05-27 14:40 UTC, bahumbert requested changes

2021-05-27 14:40 UTC, bahumbert commented on src/components/Hero.tsx
> +}
Stateless

2021-05-27 14:40 UTC, bahumbert commented on src/components/Hero.tsx
> +export default function Hero({ hero, values: values, subtitle }: Props) {
"values: values" 😋

2021-05-27 14:40 UTC, bahumbert commented on src/components/Hero.tsx
> +            <div className="bg-white h-px mb-4 w-16 md:mb-0 md:h-0 md:bg-transparent self-center"></div>
`/>` 😋

2021-05-27 14:40 UTC, bahumbert commented on src/components/HomeJoinUs.tsx
>            {
Bien vu les renommages 👌

2021-05-27 14:40 UTC, bahumbert commented on src/components/HomeOffers.tsx
> +    selectedOffer !== index ? setIsOpennedOffer(true) : setIsOpennedOffer(!isOpennedOffer)
Mets le ternaire dans `setIsOpennedOffer` 👍

2021-05-27 14:40 UTC, bahumbert commented on src/components/HomeSectors.tsx
> +    selectedSector !== index ? setIsOpennedSector(true) : setIsOpennedSector(!isOpennedSector)
Pareil ici, et je vois 2 autres soucis (peut être aussi présents plus haut, pas revérifié).
- Y-a-t-il vraiment besoin du state selectedSector (index) ? De ce que je vois autant mettre l'index direct ici non ? (Et s'il est différent de -1 ça veut dire qu'il y en a un ouvert) 🤔 
- `setIsOpennedSector(!isOpennedSector)` risque de race condition, il faut faire plutôt `setIsOpennedSector((isOpen) => !isOpen)` (un doute sur la syntaxe exacte mais c'est l'idée)

2021-05-27 14:40 UTC, bahumbert commented on src/pages/index.tsx
> +            <HomeSectors sectors={pageContent.secteurs} title={pageContent.secteurs_title} />
Haha le métier rentre 😋

2021-05-31 08:00 UTC, CedricKlodzinski commented on src/components/Hero.tsx
> +}
Elle l'est pas déjà ? Elle est pas dans le composant

2021-06-02 12:20 UTC, bahumbert commented on src/components/Hero.tsx
> +}
Ah oui haha 👌

2021-06-02 13:06 UTC, merged