Tech revamp
Agaetis-IT/agaetis-web-front pull request #74
Opened 2021-06-29 12:21 UTC by CedricKlodzinski

2021-07-06 16:01 UTC, CedricKlodzinski commented
Le commit Anti-spam, c'est... L'anti-spam

2021-07-07 14:33 UTC, bahumbert commented
Les conflits sont là 😂

2021-07-07 14:34 UTC, bahumbert commented on .eslintrc
> +    "prettier/prettier": "off",
🤔

2021-07-07 14:34 UTC, bahumbert commented on .eslintrc
> +    "@typescript-eslint/ban-ts-comment": "off",
Ca paraît pas net d'avoir des changements qu'on a reviewé précédemment 🤔

2021-07-07 15:24 UTC, bahumbert requested changes

2021-07-07 15:24 UTC, bahumbert commented on src/components/PostContent.tsx
> +                <img className="mr-4" src={Back} alt="" />
Héhé je l'ai vu !

2021-07-07 15:24 UTC, bahumbert commented on src/pages/offer/[offerSlug].tsx
> +              <img src={pageContent.offers_image1} className="block h-16" alt="" />
🤭

2021-07-07 15:24 UTC, bahumbert commented on src/pages/offer/[offerSlug].tsx
> +                    <img className="mr-4" src={Back} alt="" />
🛑

2021-07-07 15:24 UTC, bahumbert commented on src/pages/offer/[offerSlug].tsx
> +                    <img className="mr-4 h-8" src={Back} alt="" />
🏭

2021-07-07 15:24 UTC, bahumbert commented on src/pages/offer/[offerSlug].tsx
> +                <img src={pageContent.offers_image1} className="block h-12" alt="" />
🧑‍🏭

2021-07-07 15:24 UTC, bahumbert commented on src/pages/offers.tsx
> +                  <img src={allOffers[selectedOffer].offers_image1} className="block h-16" alt="" />
🥇

2021-07-07 15:24 UTC, bahumbert commented on src/pages/offers.tsx
> +                    En savoir plus <img src={Plus} className="ml-4 h-6" alt="" />
👎

2021-07-07 15:24 UTC, bahumbert commented on src/pages/offers.tsx
> +                    <img src={offre.offers_image1} className="h-8 md:h-24" alt="" />
🔢

2021-07-07 15:24 UTC, bahumbert commented on src/services/wordpressService.tsx
> +    }${category ? `&cat_name=${category}` : ''}`
`&&`

2021-07-12 12:35 UTC, CedricKlodzinski commented on src/components/Address.tsx
> +      {tel && 'Tél. ' + tel}
Je vois pas où il y en aurait besoin, ça marche très bien tel quel

2021-07-12 15:04 UTC, CedricKlodzinski commented on src/services/wordpressService.tsx
> +    }${category ? `&cat_name=${category}` : ''}`
Dans ce cas-là, ça marche pas, il me convertit `undefined` en string

2021-07-27 07:39 UTC, bahumbert commented
Reste les alt 👎 🙈

2021-07-27 08:45 UTC, merged